server:
    port: 10086
spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: 'true '
        nacos:
            discovery:
                server-addr: 81.68.64.142:8848
                group: shaoxinyu
                password: nacos
                username: nacos

